fix: migrate all the stuff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ env:
   LOG_LEVEL: debug
 
 jobs:
-  validate-preset:
+  validate-presets:
     runs-on: ubuntu-latest
     timeout-minutes: 10
 
@@ -32,3 +32,31 @@ jobs:
 
       - name: Testing ${{ matrix.file }}
         run: npx --package renovate renovate-config-validator
+
+  all-done:
+    name: All done
+    # this is the job that should be marked as required on GitHub. It's the only one that'll reliably trigger
+    # when any upstream fails: success
+    # when all upstream skips: pass
+    # when all upstream success: success
+    # combination of upstream skip and success: success
+    runs-on: ubuntu-latest
+    needs:
+      - validate-presets
+    if: |
+      always()
+    steps:
+      - name: Fail!
+        shell: bash
+        if: |
+          contains(needs.*.result, 'failure') ||
+          contains(needs.*.result, 'cancelled')
+        run: |
+          echo "One / more upstream failed or was cancelled. Failing job..."
+
+          exit 1
+
+      - name: Success!
+        shell: bash
+        run: |
+          echo "Great success!"
